[package]
name = "kul_shared_tests"
version = "0.1.0"
authors = ["Derick Eddington"]
edition = "2018"
description = "Test suites and utilities for testing both the core and the full crates."
publish = false

[dependencies]
kul_core = { path = "../core" }
kul = { path = ".." }
